### ISSUE TITLE
Diagram Generation

### ISSUE THREAD

**Issue by brotherdust** [distillpub/post--augmented-rnns#10]
The diagrams on these articles are incredible! I want to generate some for myself. However, your guide doesn't have any information on how you are generating these diagrams. Can you please clarify the process you are using as part of the guide?
Thanks!

**Comment by jbenet** [comment]
Same here. These diagrams are excellent. I'd love to be able to generate similar ones. What tooling do you use? Are there any source files we can look at?

**Comment by jbenet** [comment]
I guess just d3? is there a library of components you are using?

**Comment by colah** [comment]
Hi Jarad, Juan,

Most of our static diagrams are drawn in a vector graphics tool, like Adobe Illustrator, Sketch or Inkscape. For dynamic diagrams we generally use D3.js.

You can combine the two, by tagging elements with ids and classes in your vector graphics tool and then binding to them with d3. This is helpful for complicated diagrams where you only want to make small parts reactive.

You're absolutely right that we should say something about this in the guide.

I'm also hoping we can create a "Distill patterns" document, covering best practices for good writing and visualization, from recurring issues that come up during review.

**Comment by brotherdust** [comment]
Thanks for the encouraging response!

May I suggest a comprehensive style guide? Consistent styling is, IMO, a compelling feature, perhaps the main feature, of your platform. From a contribution perspective, it's one less thing I would have to think about. From a reviewer perspective, it provides a baseline set of expectations; using this document is the same as using this other document.

Ideally, it could be presented as a design language; a living document of basic building blocks, how to construct them, and why they are that way. Maybe I'm getting a little carried away, but it's OK to deal, right?

**Comment by brotherdust** [comment]
s/deal/dream

Stupid spell check!

**Comment by colah** [comment]
I've added a couple paragraphs to the guide about this:

![image](https://cloud.githubusercontent.com/assets/61658/24228337/bc42761c-0f30-11e7-9719-af237dc68ce0.png)

Hopefully we'll be able to start a Distill Patterns or style guide in the next week or so.

**Comment by euler16** [comment]
@colah  could u please upload some sample code u use to generate these diagrams?

**Comment by colah** [comment]
@euler16 Everything is in this repository under `public/assets`. See:

* [The Illustrator file](https://github.com/distillpub/post--augmented-rnns/blob/master/public/assets/rnn.ai) which compiles to the SVGs.

* The HTML files with JS to animate the diagrams ([example](https://github.com/distillpub/post--augmented-rnns/blob/master/public/assets/rnn_write_detail.html))
